// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	PhoneNumber string         `json:"phone_number"`
	Password    string         `json:"password"`
	Role        sql.NullString `json:"role"`
	CreatedAt   time.Time      `json:"created_at"`
}
