// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID          int64
	Username    string
	PhoneNumber string
	Password    string
	Role        sql.NullString
	CreatedAt   time.Time
}
